version: '3.7'

services:
  nginx:
    build: ./.docker/development/nginx
    container_name: foodic-nginx
    restart: unless-stopped
    ports:
      - "8100:80"
      - "444:443"
    volumes:
      - .:/var/www/html
      - ./.docker/development/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - pgsql
    networks:
      laravel:
        ipv4_address: 192.168.97.2
        aliases:
          - nginx
    env_file:
      - .env

  pgsql:
    build: ./.docker/development/pgsql
    container_name: foodic-pgsql
    volumes:
      - ./pgsqldata:/var/lib/postgresql/data
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    networks:
      laravel:
        ipv4_address: 192.168.97.3
        aliases:
          - pgsql
    env_file:
      - .env

  php:
    build: ./.docker/development/php
    container_name: foodic-php
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    ports:
      - "9002:9000"
    networks:
      laravel:
        ipv4_address: 192.168.97.4
        aliases:
          - php
    env_file:
      - .env

volumes:
  pgsqldata:

networks:
  laravel:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.97.0/24"
